export interface Product {
  id: string;
  name: string;
  brand: "epson" | "hp" | "brother" | "canon" | "xerox";
  category: "tinta" | "toner";
  color: string;
  type: string;
  capacity: string;
  compatible: string[];
  price: number;
}

export const products: Product[] = [
  // TINTA
  {
    id: "1",
    name: "Epson 664 Black",
    brand: "epson",
    category: "tinta",
    color: "Hitam",
    type: "Original",
    capacity: "70ml",
    compatible: ["L120", "L210", "L360"],
    price: 85000,
  },
  {
    id: "2",
    name: "Epson 664 Cyan",
    brand: "epson",
    category: "tinta",
    color: "Cyan",
    type: "Original",
    capacity: "70ml",
    compatible: ["L120", "L210", "L360"],
    price: 85000,
  },
  {
    id: "3",
    name: "Epson 664 Magenta",
    brand: "epson",
    category: "tinta",
    color: "Magenta",
    type: "Original",
    capacity: "70ml",
    compatible: ["L120", "L210", "L360"],
    price: 85000,
  },
  {
    id: "4",
    name: "Epson 664 Yellow",
    brand: "epson",
    category: "tinta",
    color: "Kuning",
    type: "Original",
    capacity: "70ml",
    compatible: ["L120", "L210", "L360"],
    price: 85000,
  },
  {
    id: "5",
    name: "HP 680 Black",
    brand: "hp",
    category: "tinta",
    color: "Hitam",
    type: "Cartridge Original",
    capacity: "480 halaman",
    compatible: ["HP 2335", "HP 2336", "HP 2775"],
    price: 145000,
  },
  {
    id: "6",
    name: "HP 680 Tri-Color",
    brand: "hp",
    category: "tinta",
    color: "Warna (CMY)",
    type: "Cartridge Original",
    capacity: "150 halaman",
    compatible: ["HP 2335", "HP 2336", "HP 2775"],
    price: 185000,
  },
  {
    id: "7",
    name: "Brother BT6000BK",
    brand: "brother",
    category: "tinta",
    color: "Hitam",
    type: "Original",
    capacity: "5000 halaman",
    compatible: ["T300", "T500", "T700"],
    price: 125000,
  },
  {
    id: "8",
    name: "Brother BT5000CMY",
    brand: "brother",
    category: "tinta",
    color: "Cyan/Magenta/Yellow",
    type: "Original",
    capacity: "1500 halaman",
    compatible: ["T300", "T500", "T700"],
    price: 95000,
  },
  // TONER
  {
    id: "9",
    name: "HP 85A Black Toner",
    brand: "hp",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "1600 halaman",
    compatible: ["HP P1102", "HP M1132", "HP M1212"],
    price: 450000,
  },
  {
    id: "10",
    name: "HP 12A Black Toner",
    brand: "hp",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "2000 halaman",
    compatible: ["HP 1010", "HP 1018", "HP 1020", "HP M1005"],
    price: 520000,
  },
  {
    id: "11",
    name: "Canon PG-47 Black Ink",
    brand: "canon",
    category: "tinta",
    color: "Hitam",
    type: "Tinta Original",
    capacity: "400 halaman",
    compatible: ["Canon E400", "Canon E410", "Canon E460", "Canon E470"],
    price: 145000,
  },
  {
    id: "12",
    name: "Canon CL-57 Color Ink",
    brand: "canon",
    category: "tinta",
    color: "Warna (CMY)",
    type: "Tinta Original",
    capacity: "300 halaman",
    compatible: ["Canon E400", "Canon E410", "Canon E460", "Canon E470"],
    price: 185000,
  },
  {
    id: "13",
    name: "Canon PG-810 Black Ink",
    brand: "canon",
    category: "tinta",
    color: "Hitam",
    type: "Tinta Original",
    capacity: "220 halaman",
    compatible: ["Canon MP258", "Canon MP287", "Canon MP497", "Canon MX328"],
    price: 155000,
  },
  {
    id: "14",
    name: "Canon CL-811 Color Ink",
    brand: "canon",
    category: "tinta",
    color: "Warna (CMY)",
    type: "Tinta Original",
    capacity: "244 halaman",
    compatible: ["Canon MP258", "Canon MP287", "Canon MP497", "Canon MX328"],
    price: 195000,
  },
  {
    id: "15",
    name: "Canon 328 Toner",
    brand: "canon",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "2100 halaman",
    compatible: ["Canon MF4410", "Canon MF4450", "Canon MF4710"],
    price: 480000,
  },
  {
    id: "16",
    name: "Canon 337 Toner",
    brand: "canon",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "2400 halaman",
    compatible: ["Canon MF211", "Canon MF212", "Canon MF215", "Canon MF217"],
    price: 550000,
  },
  {
    id: "17",
    name: "Xerox 106R04377 Toner",
    brand: "xerox",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "1500 halaman",
    compatible: ["Xerox B205", "Xerox B210", "Xerox B215"],
    price: 450000,
  },
  {
    id: "18",
    name: "Xerox 106R02773 Toner",
    brand: "xerox",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "3000 halaman",
    compatible: ["Xerox Phaser 3020", "Xerox WorkCentre 3025"],
    price: 580000,
  },
  {
    id: "19",
    name: "Brother TN-2260 Toner",
    brand: "brother",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "1200 halaman",
    compatible: ["Brother HL-2240", "Brother HL-2250", "Brother DCP-7060"],
    price: 380000,
  },
  {
    id: "20",
    name: "Brother TN-2280 Toner",
    brand: "brother",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "2600 halaman",
    compatible: ["Brother HL-2240", "Brother HL-2250", "Brother MFC-7360"],
    price: 490000,
  },
  {
    id: "21",
    name: "Epson M1100 Toner",
    brand: "epson",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "1000 halaman",
    compatible: ["Epson M1100", "Epson M1120"],
    price: 350000,
  },
  {
    id: "22",
    name: "Xerox 3020 Toner",
    brand: "xerox",
    category: "toner",
    color: "Hitam",
    type: "Toner Original",
    capacity: "1500 halaman",
    compatible: ["Xerox 3020", "Xerox 3025"],
    price: 420000,
  },
];
